service: draw-bolt
frameworkVersion: '3'
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: ./src/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
useDotenv: true
